spring.application.name=work
Server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/work_db
spring.datasource.username=root
spring.datasource.password=Sagar@123#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework=INFO
logging.level.com.example.work=DEBUG
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sagarsrivastava590@gmail.com
spring.mail.password=udgt iuyz diwp psic
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Imap Configuration
spring.mail.imap.host=imap.gmail.com
spring.mail.imap.port=993
spring.mail.imap.username=sagarsrivastava590@gmail.com
spring.mail.imap.password=udgt iuyz diwp psic
spring.mail.properties.mail.imap.ssl.enable=true
spring.mail.properties.mail.imap.auth=true
spring.mail.imap.folder=INBOX
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

##sping ai configuration
#spring.ai.api-key=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
#spring.ai.model=gpt-3.5-turbo
spring.ai.openai.api-key=AQ.Ab8RN6LyckCDWtOoNfEajsDksDKIFoAvAbL8Mttyjx3pOY6e2Q
spring.ai.openai.chat-options.model=localModel
#spring.ai.openai.api-key=dummy
spring.ai.openai.api-base-url=http://localhost:1234