spring.application.name=work
Server.port=8080

# Database Configuration
spring.datasource.url=${jdbc_url}
spring.datasource.username=${jdbc_username}
spring.datasource.password=${jdbc_PWD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework=INFO
logging.level.com.example.work=DEBUG
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GmailID}
spring.mail.password=${GmailAppPassword}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Imap Configuration
spring.mail.imap.host=imap.gmail.com
spring.mail.imap.port=993
spring.mail.imap.username=${GmailID}
spring.mail.imap.password=${GmailAppPassword_IMAP}
spring.mail.properties.mail.imap.ssl.enable=true
spring.mail.properties.mail.imap.auth=true
spring.mail.imap.folder=INBOX
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


##sping ai configuration
#spring.ai.model=gpt-3.5-turbo
spring.ai.openai.api-key=${api-key-dummy}
spring.ai.openai.chat-options.model=localModel
#spring.ai.openai.api-key=dummy
spring.ai.openai.api-base-url=${base-url}